name: Student Management System CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run project check
        run: |
          echo "Student Management System"
          echo "GitHub Actions workflow executed successfully!"
